### ISSUE TITLE
API return 502 HTTP error when trying to get full warning

### ISSUE THREAD

**Issue by eziocangialosi** [hacf-fr/meteofrance-api#629]
**Describe the bug**
When I try to get the full warnign with the "get_warning_full()" method, I get a 502 HTTP error.
The  "get_warning_full()" method seams only work with Paris (75)

**log**

```
Traceback (most recent call last):
  File "/var/www/html/weather/weather.py", line 137, in <module>
    get_weather(WXCity)
  File "/var/www/html/weather/weather.py", line 46, in get_weather
    wx_warns = getWarnsFromAPI(anMeteoAPI)
  File "/var/www/html/weather/weather.py", line 35, in getWarnsFromAPI
    my_place_warn = aMeteoAPI.client.get_warning_full(aMeteoAPI.my_place.admin2)
  File "/home/pi/.local/lib/python3.9/site-packages/meteofrance_api/client.py", line 275, in get_warning_full
    resp = self.session.request("get", "warning/full", params={"domain": domain})
  File "/home/pi/.local/lib/python3.9/site-packages/meteofrance_api/session.py", line 52, in request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://webservice.meteofrance.com/warning/full?token=__<token>__&domain=60
```

**Comment by Tech-User42** [comment]
Got the same issue, it seams that the endpoint got updated but not in the python lib
![image](https://github.com/hacf-fr/meteofrance-api/assets/60147737/d688d73a-8bc2-4daf-9f67-6d87dfafcc87)
